### ISSUE TITLE
Tunnel opens on the multi tab restricting the ability to open new tabs.

### ISSUE THREAD

**Issue by ananya-rajput** [dailykit/settings-app#3]
Tunnels will open inside the tab so that the user is able to perform multiple functions at once.
Issue: 
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/59871793/75958138-a1988000-5ee1-11ea-978f-cc75509c1efd.png">

Solution:
<img width="812" alt="image" src="https://user-images.githubusercontent.com/59871793/75958336-005df980-5ee2-11ea-938f-3d2f99aeefa7.png">

**Comment by prvnbist** [comment]
Resolved in @dailykit/ui v0.6.66 - [fix: restrict tunnel to within tab](https://github.com/dailykit/dailykit-ui/commit/68b63b2218ef3723a9f4094b53ecadc6c5cac693)
